# Generated by Django 4.1.3 on 2022-11-30 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_bid_user_id_alter_comment_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
