# Generated by Django 4.1.3 on 2022-11-30 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_remove_bid_listing_id_remove_bid_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='wishlist',
        ),
    ]
