# Generated by Django 4.1.3 on 2022-12-06 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_wishlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WishList',
            new_name='Watchlist',
        ),
    ]
